### ISSUE TITLE
It seems not work using pnpm and preinstall script

### ISSUE THREAD

**Issue by xiangqunXiao** [pnpm/only-allow#11] opened 2022-06-07 04:19 UTC
# steps
- add npm script:
```
"preinstall": "npx only-allow pnpm"
```
- input `npm install` in terminal
- get result from terminal
![image](https://user-images.githubusercontent.com/95326074/172294913-f56efaf4-06c7-481b-a2aa-016c4443e73b.png)

From the screenshot above, developer can not clear know what it means. I am not sure whether `only-allow` works or not.

**Comment by Anxium** [comment] 2022-06-10 07:03
Are you using macOS ?
- If yes, it's a duplicate of this issue #3
- Otherwise, it might be related

**Comment by Anxium** [comment] 2022-06-10 08:11
If you are using npm v7 or +, the issue is not coming from only-allow. See this issue npm/cli#2660
If you try with yarn or pnpm, it will works fine

**Comment by ERUIHNIYHBKBNF** [comment] 2023-08-02 02:18
When using npm v7+, I changed the script to be like `npx -y only-allow pnpm` just as what [pnpm doc](https://pnpm.io/only-allow-pnpm) said, and it works.

**Closed** 2023-08-17 14:49 UTC

**Comment by justforuse** [comment] 2023-12-06 03:18
> When using npm v7+, I changed the script to be like `npx -y only-allow pnpm` just as what [pnpm doc](https://pnpm.io/only-allow-pnpm) said, and it works.

I have add this script under npm v8, but not work. it install all packages, then echo the message after installation

**Comment by c0nd3v** [comment] 2024-01-13 18:51
> > When using npm v7+, I changed the script to be like `npx -y only-allow pnpm` just as what [pnpm doc](https://pnpm.io/only-allow-pnpm) said, and it works.
> 
> I have add this script under npm v8, but not work. it install all packages, then echo the message after installation

I have the same problem

**Comment by karthikappiah** [comment] 2025-07-21 21:40
Another solution could be to avoid the package `only-allow` altogether by setting the `.npmrc` configuration variable `engine-strict` as `true` and specify PNPM as the enforced package manager in your `package.json`.

This [comment](https://github.com/pnpm/only-allow/issues/33#issuecomment-3094948348) describes each step in more detail. If this workaround helps you out, please upvote my [pull request](https://github.com/pnpm/pnpm.io/pull/692#issue-3250063805) so we get more eyes to add the workaround to the docs!
